name: CI

on:
  push:
  pull_request:

jobs:
  build-manylinux:
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        env:
          TRAVIS_OS_NAME: linux
          PYTHON: ${{ matrix.python }}
        run: |
          bash .github/workflows/deploy.sh
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: python_bindings/dist

  release-pypi:
    name: Release PyPI.org
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/dev-ci')
    needs: [build-manylinux]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
